Create cid with ex cid
dwyl/cid pull request #21
Opened 2019-01-28 12:24 UTC by RobStallion

Create functions that create same CIDs as IPFS. Function takes a string, map or struct.

Currently uses ex_cid

2019-01-28 19:16 UTC, nelsonic commented on lib/ex_cid.ex
> +defmodule ExCid do
https://hex.pm/packages/excid name available on hex.pm ✅ 
![image](https://user-images.githubusercontent.com/194400/51860270-1e494a00-2331-11e9-8e79-162bf72230fc.png)

2019-01-28 19:18 UTC, nelsonic commented on mix.exs
> +      {:cid, git: "git@github.com:SimonLab/ex-cid.git"}
This project should not have a dependency on `ex-cid`.

2019-01-28 21:45 UTC, RobStallion commented
@nelsonic I have updated this now 👍

2019-01-29 09:19 UTC, RobStallion commented on .travis.yml
> +language: elixir
👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 

Good addition @nelsonic

2019-01-29 09:24 UTC, nelsonic requested changes
@RobStallion this is looking _good_ so far and I _could_ just _merge_ it. 
But we _both_ know it's not "ready" to be used by another project.
 
Please add tests for more "complex" data e.g: 
```elixir
animal = %{
  name: "Rex",
  type: "dog",
  legs: 4
}
```
or
```elixir
task = %{
  uid: 1,
  title: "Get into the top 1% of people in my chosen field of expertise https://git.io/top",
  done: false
}
```
Then Document it like your _life_ depends on it. 📝 
For this you will need to approach it with a ["Beginners Mind"](https://en.wikipedia.org/wiki/Shoshin) ...
Look at the code & docs with a fresh pair of eyes and ask yourself:
would a _complete_ beginner understand _everything_ about this?
If the answer is no (_which, hint: at this point it should be..._), add in-line comments
until you feel that the code/examples could be understood by someone on their _first_ day of learning elixir.

2019-01-29 12:03 UTC, Danwhy commented on lib/cid.ex
> +  Currently only uses the "raw" codec
Maybe add a little more info on what a v1 CID or "raw" codec is. Just a link would probably be fine, even if it's to elsewhere in this repo.

2019-01-29 12:03 UTC, Danwhy commented on lib/cid.ex
> +  is identical to one what will be returned from IPFS if the same data is
A link to an explanation of what IPFS is might be good here

2019-01-29 12:03 UTC, Danwhy commented on lib/cid.ex
> +    |> B58.encode58()
Could do with a brief explanation of B58

2019-01-29 12:03 UTC, Danwhy commented on lib/cid.ex
> +  defp create_cid_suffix(multihash), do: <<1>> <> "U" <> multihash
A small comment on the binary syntax might be useful to people unfamiliar with it

2019-01-29 12:03 UTC, Danwhy commented on lib/cid.ex
> +  defp create_multihash(%_{} = struct) do
A brief explanation of how this pattern matching works would be useful for beginners

2019-01-29 12:03 UTC, Danwhy commented on lib/cid.ex
> +    digest = :crypto.hash(:sha256, str)
Explaining in the comments that this is an erlang function would be good for beginners

2019-01-29 12:06 UTC, RobStallion commented on lib/cid.ex
> +    |> B58.encode58()
Just added this in [one of the latest commits](https://github.com/dwyl/cid/pull/21/commits/8a21996c8b71957e14fa8beeac6df69c3ba71551). Thanks for pointing that out

2019-01-29 12:07 UTC, RobStallion commented
@Danwhy Thanks for all the point on the documentation updates that can be done here. I'll get on those right away. All really good points thanks 👍

2019-01-29 12:30 UTC, nelsonic commented on lib/cid.ex
> +  is identical to one what will be returned from IPFS if the same data is
Please link to it in the `README.md` in https://github.com/dwyl/learn-ipfs i.e. "What is IPFS?" and if we don't already have the section, we should add it ASAP see: https://github.com/dwyl/learn-ipfs/issues/1#issuecomment-458522501

2019-01-29 12:58 UTC, RobStallion commented
@nelsonic @Danwhy Have updated the pr based on your feedback.

2019-01-29 13:30 UTC, nelsonic requested changes
@RobStallion looking better. 👍 
[_Again_](https://youtu.be/fhrNgXJ__n8?t=217) ... 🥋

2019-01-29 14:03 UTC, nelsonic commented on lib/cid.ex
> +  @spec cid(String.t | map() | struct()) :: String.t
👍

2019-01-30 10:28 UTC, nelsonic commented
@RobStallion & @Danwhy _good_ work on adding property-based-testing. 🎉 
_Showcase_ your work by adding a Travis-CI and Codecov Badge ... 😉

2019-01-30 10:38 UTC, RobStallion commented
@nelsonic Will do.

2019-01-30 14:00 UTC, nelsonic approved these changes
@RobStallion looking _much_ better. Thanks! 🎉 
Can't _wait_ to apply this to our https://github.com/dwyl/phoenix-ecto-append-only-log-example 😉

2019-01-30 14:00 UTC, merged